<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_maps"
 *
 * Auto generated by Extension Builder 2019-02-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'RKW Maps',
    'description'      => 'Adds interactive maps to show information based on german districts',
    'category'         => 'plugin',
    'author'           => 'Christian Dilger',
    'author_email'     => 'c.dilger@addorange.de',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'clearCacheOnLoad' => 0,
    'version'          => '10.4.1',
    'constraints'      => [
        'depends'   => [
            'typo3' => '10.4.0-10.4.99',
            'core_extended' => '10.4.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests'  => []
    ]
];
