CREATE TABLE `tx_rkwmaps_domain_model_district` INSERT INTO tx_rkwmp(
    uid int(11) NOT NULL auto_increment,
    pid int(11) NOT NULL DEFAULT '0',
    name varchar(255) NOT NULL DEFAULT '',
    slug varchar(255) NOT NULL DEFAULT '',

	PRIMARY KEY (uid),
	KEY parent (pid)
);

INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (1, 0, 'Aachen', 'aachen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (2, 0, 'Ahrweiler', 'ahrweiler');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (3, 0, 'Aichach-Friedberg', 'aichach-friedberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (4, 0, 'Alb-Donau-Kreis', 'alb-donau-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (5, 0, 'Altenburger Land', 'altenburger-land');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (6, 0, 'Altenkirchen', 'altenkirchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (7, 0, 'Altmarkkreis Salzwedel', 'altmarkkreis-salzwedel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (8, 0, 'Altötting', 'altoetting');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (9, 0, 'Alzey-Worms', 'alzey-worms');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (10, 0, 'Amberg', 'amberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (11, 0, 'Amberg-Sulzbach', 'amberg-sulzbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (12, 0, 'Ammerland', 'ammerland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (13, 0, 'Anhalt-Bitterfeld', 'anhalt-bitterfeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (14, 0, 'Ansbach', 'ansbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (15, 0, 'Aschaffenburg', 'aschaffenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (16, 0, 'Augsburg', 'augsburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (17, 0, 'Aurich', 'aurich');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (18, 0, 'Bad Dürkheim', 'bad-duerkheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (19, 0, 'Bad Kissingen', 'bad-kissingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (20, 0, 'Bad Kreuznach', 'bad-kreuznach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (21, 0, 'Bad Tölz-Wolfratshausen', 'bad-toelz-wolfratshausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (22, 0, 'Baden-Baden', 'baden-baden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (23, 0, 'Bamberg', 'bamberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (24, 0, 'Barnim', 'barnim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (25, 0, 'Bautzen', 'bautzen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (26, 0, 'Bayreuth', 'bayreuth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (27, 0, 'Berchtesgadener Land', 'berchtesgadener-land');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (28, 0, 'Bergstraße', 'bergstrasse');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (29, 0, 'Berlin', 'berlin');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (30, 0, 'Bernkastel-Wittlich', 'bernkastel-wittlich');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (31, 0, 'Biberach', 'biberach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (32, 0, 'Bielefeld', 'bielefeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (33, 0, 'Birkenfeld', 'birkenfeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (34, 0, 'Böblingen', 'boeblingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (35, 0, 'Bochum', 'bochum');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (36, 0, 'Bodenseekreis', 'bodenseekreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (37, 0, 'Bonn', 'bonn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (38, 0, 'Börde', 'boerde');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (39, 0, 'Borken', 'borken');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (40, 0, 'Bottrop', 'bottrop');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (41, 0, 'Brandenburg', 'brandenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (42, 0, 'Braunschweig', 'braunschweig');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (43, 0, 'Breisgau-Hochschwarzwald', 'breisgau-hochschwarzwald');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (44, 0, 'Bremen', 'bremen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (45, 0, 'Bremerhaven', 'bremerhaven');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (46, 0, 'Burgenlandkreis', 'burgenlandkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (47, 0, 'Calw', 'calw');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (48, 0, 'Celle', 'celle');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (49, 0, 'Cham', 'cham');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (50, 0, 'Chemnitz', 'chemnitz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (51, 0, 'Cloppenburg', 'cloppenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (52, 0, 'Coburg', 'coburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (53, 0, 'Cochem-Zell', 'cochem-zell');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (54, 0, 'Coesfeld', 'coesfeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (55, 0, 'Cottbus', 'cottbus');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (56, 0, 'Cuxhaven', 'cuxhaven');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (57, 0, 'Dachau', 'dachau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (58, 0, 'Dahme-Spreewald', 'dahme-spreewald');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (59, 0, 'Darmstadt', 'darmstadt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (60, 0, 'Darmstadt-Dieburg', 'darmstadt-dieburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (61, 0, 'Deggendorf', 'deggendorf');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (62, 0, 'Delmenhorst', 'delmenhorst');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (63, 0, 'Dessau-Roßlau', 'dessau-rosslau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (64, 0, 'Diepholz', 'diepholz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (65, 0, 'Dillingen', 'dillingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (66, 0, 'Dingolfing-Landau', 'dingolfing-landau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (67, 0, 'Dithmarschen', 'dithmarschen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (68, 0, 'Donau-Ries', 'donau-ries');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (69, 0, 'Donnersbergkreis', 'donnersbergkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (70, 0, 'Dortmund', 'dortmund');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (71, 0, 'Dresden', 'dresden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (72, 0, 'Duisburg', 'duisburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (73, 0, 'Düren', 'dueren');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (74, 0, 'Düsseldorf', 'duesseldorf');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (75, 0, 'Ebersberg', 'ebersberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (76, 0, 'Eichsfeld', 'eichsfeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (77, 0, 'Eichstätt', 'eichstaett');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (78, 0, 'Eifelkreis Bitburg-Prüm', 'eifelkreis-bitburg-pruem');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (79, 0, 'Eisenach', 'eisenach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (80, 0, 'Elbe-Elster', 'elbe-elster');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (81, 0, 'Emden', 'emden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (82, 0, 'Emmendingen', 'emmendingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (83, 0, 'Emsland', 'emsland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (84, 0, 'Ennepe-Ruhr-Kreis', 'ennepe-ruhr-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (85, 0, 'Enzkreis', 'enzkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (86, 0, 'Erding', 'erding');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (87, 0, 'Erfurt', 'erfurt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (88, 0, 'Erlangen', 'erlangen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (89, 0, 'Erlangen-Höchstadt', 'erlangen-hoechstadt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (90, 0, 'Erzgebirgskreis', 'erzgebirgskreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (91, 0, 'Essen', 'essen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (92, 0, 'Esslingen', 'esslingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (93, 0, 'Euskirchen', 'euskirchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (94, 0, 'Flensburg', 'flensburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (95, 0, 'Forchheim', 'forchheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (96, 0, 'Frankenthal', 'frankenthal');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (97, 0, 'Frankfurt', 'frankfurt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (98, 0, 'Frankfurt am Main', 'frankfurt-am-main');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (99, 0, 'Freiburg', 'freiburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (100, 0, 'Freising', 'freising');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (101, 0, 'Freudenstadt', 'freudenstadt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (102, 0, 'Freyung-Grafenau', 'freyung-grafenau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (103, 0, 'Friesland', 'friesland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (104, 0, 'Fulda', 'fulda');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (105, 0, 'Fürstenfeldbruck', 'fuerstenfeldbruck');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (106, 0, 'Fürth', 'fuerth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (107, 0, 'Garmisch-Partenkirchen', 'garmisch-partenkirchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (108, 0, 'Gelsenkirchen', 'gelsenkirchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (109, 0, 'Gera', 'gera');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (110, 0, 'Germersheim', 'germersheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (111, 0, 'Gießen', 'giessen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (112, 0, 'Gifhorn', 'gifhorn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (113, 0, 'Göppingen', 'goeppingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (114, 0, 'Görlitz', 'goerlitz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (115, 0, 'Goslar', 'goslar');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (116, 0, 'Gotha', 'gotha');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (117, 0, 'Göttingen', 'goettingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (118, 0, 'Grafschaft Bentheim', 'grafschaft-bentheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (119, 0, 'Greiz', 'greiz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (120, 0, 'Groß-Gerau', 'gross-gerau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (121, 0, 'Günzburg', 'guenzburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (122, 0, 'Gütersloh', 'guetersloh');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (123, 0, 'Hagen', 'hagen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (124, 0, 'Halle', 'halle');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (125, 0, 'Hamburg', 'hamburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (126, 0, 'Hameln-Pyrmont', 'hameln-pyrmont');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (127, 0, 'Hamm', 'hamm');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (128, 0, 'Hannover', 'hannover');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (129, 0, 'Harburg', 'harburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (130, 0, 'Harz', 'harz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (131, 0, 'Haßberge', 'hassberge');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (132, 0, 'Havelland', 'havelland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (133, 0, 'Heidekreis', 'heidekreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (134, 0, 'Heidelberg', 'heidelberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (135, 0, 'Heidenheim', 'heidenheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (136, 0, 'Heilbronn', 'heilbronn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (137, 0, 'Heinsberg', 'heinsberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (138, 0, 'Helmstedt', 'helmstedt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (139, 0, 'Herford', 'herford');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (140, 0, 'Herne', 'herne');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (141, 0, 'Hersfeld-Rotenburg', 'hersfeld-rotenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (142, 0, 'Herzogtum-Lauenburg', 'herzogtum-lauenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (143, 0, 'Hildesheim', 'hildesheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (144, 0, 'Hochsauerlandkreis', 'hochsauerlandkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (145, 0, 'Hochtaunuskreis', 'hochtaunuskreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (146, 0, 'Hof', 'hof');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (147, 0, 'Hohenlohekreis', 'hohenlohekreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (148, 0, 'Holzminden', 'holzminden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (149, 0, 'Höxter', 'hoexter');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (150, 0, 'Ilm-Kreis', 'ilm-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (151, 0, 'Ingolstadt', 'ingolstadt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (152, 0, 'Jena', 'jena');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (153, 0, 'Jerichower Land', 'jerichower-land');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (154, 0, 'Kaiserslautern', 'kaiserslautern');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (155, 0, 'Karlsruhe', 'karlsruhe');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (156, 0, 'Kassel', 'kassel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (157, 0, 'Kaufbeuren', 'kaufbeuren');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (158, 0, 'Kelheim', 'kelheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (159, 0, 'Kempten', 'kempten');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (160, 0, 'Kiel', 'kiel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (161, 0, 'Kiel', 'kiel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (162, 0, 'Kitzingen', 'kitzingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (163, 0, 'Kleve', 'kleve');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (164, 0, 'Koblenz', 'koblenz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (165, 0, 'Köln', 'koeln');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (166, 0, 'Konstanz', 'konstanz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (167, 0, 'Konstanz', 'konstanz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (168, 0, 'Krefeld', 'krefeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (169, 0, 'Kronach', 'kronach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (170, 0, 'Kulmbach', 'kulmbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (171, 0, 'Kusel', 'kusel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (172, 0, 'Lahn-Dill-Kreis', 'lahn-dill-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (173, 0, 'Landau', 'landau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (174, 0, 'Landkreis Ansbach', 'landkreis-ansbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (175, 0, 'Landkreis Aschaffenburg', 'landkreis-aschaffenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (176, 0, 'Landkreis Augsburg', 'landkreis-augsburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (177, 0, 'Landkreis Bamberg', 'landkreis-bamberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (178, 0, 'Landkreis Bayreuth', 'landkreis-bayreuth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (179, 0, 'Landkreis Coburg', 'landkreis-coburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (180, 0, 'Landkreis Fürth', 'landkreis-fuerth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (181, 0, 'Landkreis Heilbronn', 'landkreis-heilbronn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (182, 0, 'Landkreis Hof', 'landkreis-hof');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (183, 0, 'Landkreis Kaiserslautern', 'landkreis-kaiserslautern');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (184, 0, 'Landkreis Karlsruhe', 'landkreis-karlsruhe');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (185, 0, 'Landkreis Kassel', 'landkreis-kassel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (186, 0, 'Landkreis Landshut', 'landkreis-landshut');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (187, 0, 'Landkreis Leipzig', 'landkreis-leipzig');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (188, 0, 'Landkreis München', 'landkreis-muenchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (189, 0, 'Landkreis Offenbach', 'landkreis-offenbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (190, 0, 'Landkreis Osnabrück', 'landkreis-osnabrueck');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (191, 0, 'Landkreis Passau', 'landkreis-passau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (192, 0, 'Landkreis Regensburg', 'landkreis-regensburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (193, 0, 'Landkreis Rosenheim', 'landkreis-rosenheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (194, 0, 'Landkreis Rostock', 'landkreis-rostock');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (195, 0, 'Landkreis Schweinfurt', 'landkreis-schweinfurt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (196, 0, 'Landkreis Würzburg', 'landkreis-wuerzburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (197, 0, 'Landsberg am Lech', 'landsberg-am-lech');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (198, 0, 'Landshut', 'landshut');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (199, 0, 'Leer', 'leer');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (200, 0, 'Leipzig', 'leipzig');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (201, 0, 'Leverkusen', 'leverkusen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (202, 0, 'Lichtenfels', 'lichtenfels');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (203, 0, 'Limburg-Weilburg', 'limburg-weilburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (204, 0, 'Lindau', 'lindau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (205, 0, 'Lippe', 'lippe');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (206, 0, 'Lörrach', 'loerrach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (207, 0, 'Lübeck', 'luebeck');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (208, 0, 'Lüchow-Dannenberg', 'luechow-dannenberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (209, 0, 'Ludwigsburg', 'ludwigsburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (210, 0, 'Ludwigshafen', 'ludwigshafen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (211, 0, 'Ludwigslust-Parchim', 'ludwigslust-parchim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (212, 0, 'Lüneburg', 'lueneburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (213, 0, 'Magdeburg', 'magdeburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (214, 0, 'Main-Kinzig-Kreis', 'main-kinzig-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (215, 0, 'Main-Spessart', 'main-spessart');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (216, 0, 'Main-Tauber-Kreis', 'main-tauber-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (217, 0, 'Main-Taunus-Kreis', 'main-taunus-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (218, 0, 'Mainz', 'mainz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (219, 0, 'Mainz-Bingen', 'mainz-bingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (220, 0, 'Mannheim', 'mannheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (221, 0, 'Mansfeld-Südharz', 'mansfeld-suedharz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (222, 0, 'Marburg-Biedenkopf', 'marburg-biedenkopf');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (223, 0, 'Märkisch-Oderland', 'maerkisch-oderland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (224, 0, 'Märkischer Kreis', 'maerkischer-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (225, 0, 'Mayen-Koblenz', 'mayen-koblenz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (226, 0, 'Mecklenburgische-Seenplatte', 'mecklenburgische-seenplatte');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (227, 0, 'Meißen', 'meissen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (228, 0, 'Memmingen', 'memmingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (229, 0, 'Merzig-Wadern', 'merzig-wadern');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (230, 0, 'Mettmann', 'mettmann');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (231, 0, 'Miesbach', 'miesbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (232, 0, 'Miltenberg', 'miltenberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (233, 0, 'Minden-Lübbecke', 'minden-luebbecke');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (234, 0, 'Mittelsachsen', 'mittelsachsen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (235, 0, 'Mönchengladbach', 'moenchengladbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (236, 0, 'Mühldorf am Inn', 'muehldorf-am-inn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (237, 0, 'Mülheim', 'muelheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (238, 0, 'München', 'muenchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (239, 0, 'Münster', 'muenster');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (240, 0, 'Neckar-Odenwald-Kreis', 'neckar-odenwald-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (241, 0, 'Neu-Ulm', 'neu-ulm');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (242, 0, 'Neuburg-Schrobenhausen', 'neuburg-schrobenhausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (243, 0, 'Neumarkt in der Oberpfalz', 'neumarkt-in-der-oberpfalz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (244, 0, 'Neumünster', 'neumuenster');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (245, 0, 'Neunkirchen', 'neunkirchen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (246, 0, 'Neustadt - Bad Windsheim', 'neustadt-bad-windsheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (247, 0, 'Neustadt an der Waldnaab', 'neustadt-an-der-waldnaab');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (248, 0, 'Neustadt an der Weinstraße', 'neustadt-an-der-weinstrasse');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (249, 0, 'Neuwied', 'neuwied');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (250, 0, 'Nienburg', 'nienburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (251, 0, 'Nordfriesland', 'nordfriesland');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (252, 0, 'Nordhausen', 'nordhausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (253, 0, 'Nordsachsen', 'nordsachsen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (254, 0, 'Nordwest-Mecklenburg', 'nordwest-mecklenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (255, 0, 'Northeim', 'northeim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (256, 0, 'Nürnberg', 'nuernberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (257, 0, 'Nürnberger Land', 'nuernberger-land');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (258, 0, 'Oberallgäu', 'unterallgaeu');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (259, 0, 'Oberbergischer Kreis', 'oberbergischer-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (260, 0, 'Oberhausen', 'oberhausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (261, 0, 'Oberhavel', 'oberhavel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (262, 0, 'Oberspreewald-Lausitz', 'oberspreewald-lausitz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (263, 0, 'Odenwaldkreis', 'odenwaldkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (264, 0, 'Oder-Spree', 'oder-spree');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (265, 0, 'Offenbach', 'offenbach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (266, 0, 'Oldenburg', 'oldenburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (267, 0, 'Olpe', 'olpe');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (268, 0, 'Ortenaukreis', 'ortenaukreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (269, 0, 'Osnabrück', 'osnabrueck');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (270, 0, 'Ostalbkreis', 'ostalbkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (271, 0, 'Ostallgäu', 'ostallgaeu');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (272, 0, 'Osterholz', 'osterholz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (273, 0, 'Ostholstein', 'ostholstein');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (274, 0, 'Ostprignitz-Ruppin', 'ostprignitz-ruppin');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (275, 0, 'Paderborn', 'paderborn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (276, 0, 'Passau', 'passau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (277, 0, 'Peine', 'peine');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (278, 0, 'Pfaffenhofen', 'pfaffenhofen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (279, 0, 'Pforzheim', 'pforzheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (280, 0, 'Pinneberg', 'pinneberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (281, 0, 'Pirmasens', 'pirmasens');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (282, 0, 'Plön', 'ploen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (283, 0, 'Potsdam', 'potsdam');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (284, 0, 'Potsdam-Mittelmark', 'potsdam-mittelmark');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (285, 0, 'Prignitz', 'prignitz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (286, 0, 'Rastatt', 'rastatt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (287, 0, 'Ravensburg', 'ravensburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (288, 0, 'Recklinghausen', 'recklinghausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (289, 0, 'Regen', 'regen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (290, 0, 'Regensburg', 'regensburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (291, 0, 'Rems-Murr-Kreis', 'rems-murr-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (292, 0, 'Remscheid', 'remscheid');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (293, 0, 'Rendsburg-Eckernförde', 'rendsburg-eckernfoerde');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (294, 0, 'Reutlingen', 'reutlingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (295, 0, 'Rhein-Erft-Kreis', 'rhein-erft-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (296, 0, 'Rhein-Hunsrück-Kreis', 'rhein-hunsrueck-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (297, 0, 'Rhein-Kreis Neuss', 'rhein-kreis-neuss');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (298, 0, 'Rhein-Lahn-Kreis', 'rhein-lahn-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (299, 0, 'Rhein-Neckar-Kreis', 'rhein-neckar-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (300, 0, 'Rhein-Pfalz-Kreis', 'rhein-pfalz-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (301, 0, 'Rhein-Sieg-Kreis', 'rhein-sieg-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (302, 0, 'Rheingau-Taunus-Kreis', 'rheingau-taunus-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (303, 0, 'Rheinisch-Bergischer Kreis', 'rheinisch-bergischer-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (304, 0, 'Rhön-Grabfeld', 'rhoen-grabfeld');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (305, 0, 'Rosenheim', 'rosenheim');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (306, 0, 'Rostock', 'rostock');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (307, 0, 'Rotenburg (Wümme)', 'rotenburg-wuemme');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (308, 0, 'Roth', 'roth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (309, 0, 'Rottal-Inn', 'rottal-inn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (310, 0, 'Rottweil', 'rottweil');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (311, 0, 'Saale-Holzland-Kreis', 'saale-holzland-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (312, 0, 'Saale-Orla-Kreis', 'saale-orla-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (313, 0, 'Saalekreis', 'saalekreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (314, 0, 'Saalfeld-Rudolstadt', 'saalfeld-rudolstadt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (315, 0, 'Saarbrücken', 'saarbruecken');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (316, 0, 'Saarlouis', 'saarlouis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (317, 0, 'Saarpfalz-Kreis', 'saarpfalz-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (318, 0, 'Sächsische Schweiz - Osterzgebirge', 'saechsische-schweiz-osterzgebirge');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (319, 0, 'Salzgitter', 'salzgitter');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (320, 0, 'Salzlandkreis', 'salzlandkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (321, 0, 'Schaumburg', 'schaumburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (322, 0, 'Schleswig-Flensburg', 'schleswig-flensburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (323, 0, 'Schmalkalden-Meiningen', 'schmalkalden-meiningen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (324, 0, 'Schwabach', 'schwabach');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (325, 0, 'Schwäbisch Hall', 'schwaebisch-hall');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (326, 0, 'Schwalm-Eder-Kreis', 'schwalm-eder-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (327, 0, 'Schwandorf', 'schwandorf');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (328, 0, 'Schwarzwald-Baar-Kreis', 'schwarzwald-baar-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (329, 0, 'Schweinfurt', 'schweinfurt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (330, 0, 'Schwerin', 'schwerin');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (331, 0, 'Segeberg', 'segeberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (332, 0, 'Siegen-Wittgenstein', 'siegen-wittgenstein');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (333, 0, 'Sigmaringen', 'sigmaringen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (334, 0, 'Soest', 'soest');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (335, 0, 'Solingen', 'solingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (336, 0, 'Sömmerda', 'soemmerda');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (337, 0, 'Sonneberg', 'sonneberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (338, 0, 'Speyer', 'speyer');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (339, 0, 'Spree-Neiße', 'spree-neisse');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (340, 0, 'St. Wendel', 'st-wendel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (341, 0, 'Stade', 'stade');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (342, 0, 'Starnberg', 'starnberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (343, 0, 'Steinfurt', 'steinfurt');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (344, 0, 'Stendal', 'stendal');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (345, 0, 'Stormarn', 'stormarn');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (346, 0, 'Straubing', 'straubing');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (347, 0, 'Straubing-Bogen', 'straubing-bogen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (348, 0, 'Stuttgart', 'stuttgart');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (349, 0, 'Südliche Weinstraße', 'suedliche-weinstrasse');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (350, 0, 'Südwestpfalz', 'suedwestpfalz');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (351, 0, 'Suhl', 'suhl');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (352, 0, 'Teltow-Fläming', 'teltow-flaeming');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (353, 0, 'Tirschenreuth', 'tirschenreuth');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (354, 0, 'Traunstein', 'traunstein');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (355, 0, 'Trier', 'trier');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (356, 0, 'Trier-Saarburg', 'trier-saarburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (357, 0, 'Tübingen', 'tuebingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (358, 0, 'Tuttlingen', 'tuttlingen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (359, 0, 'Uckermark', 'uckermark');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (360, 0, 'Uelzen', 'uelzen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (361, 0, 'Ulm', 'ulm');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (362, 0, 'Unna', 'unna');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (363, 0, 'Unstrut-Hainich-Kreis', 'unstrut-hainich-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (364, 0, 'Unterallgäu', 'unterallgaeu');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (365, 0, 'Vechta', 'vechta');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (366, 0, 'Verden', 'verden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (367, 0, 'Viersen', 'viersen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (368, 0, 'Vogelsbergkreis', 'vogelsbergkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (369, 0, 'Vogtlandkreis', 'vogtlandkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (370, 0, 'Vorpommern-Greifswald', 'vorpommern-greifswald');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (371, 0, 'Vorpommern-Rügen', 'vorpommern-ruegen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (372, 0, 'Vulkaneifel', 'vulkaneifel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (373, 0, 'Waldeck-Frankenberg', 'waldeck-frankenberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (374, 0, 'Waldshut', 'waldshut');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (375, 0, 'Warendorf', 'warendorf');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (376, 0, 'Wartburgkreis', 'wartburgkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (377, 0, 'Weiden', 'weiden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (378, 0, 'Weilheim-Schongau', 'weilheim-schongau');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (379, 0, 'Weimar', 'weimar');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (380, 0, 'Weimarer Land', 'weimarer-land');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (381, 0, 'Weißenburg - Gunzenhausen', 'weissenburg-gunzenhausen');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (382, 0, 'Werra-Meißner-Kreis', 'werra-meissner-kreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (383, 0, 'Wesel', 'wesel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (384, 0, 'Wesermarsch', 'wesermarsch');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (385, 0, 'Westerwaldkreis', 'westerwaldkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (386, 0, 'Wetteraukreis', 'wetteraukreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (387, 0, 'Wiesbaden', 'wiesbaden');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (388, 0, 'Wilhelmshaven', 'wilhelmshaven');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (389, 0, 'Wittenberg', 'wittenberg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (390, 0, 'Wittmund', 'wittmund');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (391, 0, 'Wolfenbüttel', 'wolfenbuettel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (392, 0, 'Wolfsburg', 'wolfsburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (393, 0, 'Worms', 'worms');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (394, 0, 'Wunsiedel', 'wunsiedel');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (395, 0, 'Wuppertal', 'wuppertal');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (396, 0, 'Würzburg', 'wuerzburg');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (397, 0, 'Zollernalbkreis', 'zollernalbkreis');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (398, 0, 'Zweibrücken', 'zweibruecken');
INSERT INTO `tx_rkwmaps_domain_model_district` (`uid`, `pid`, `name`, `slug`) VALUES (399, 0, 'Zwickau', 'zwickau');
